### PR TITLE
Added devise for authenetication (it is way easier than you think).

### PR DESCRIPTION
**Pull request by tr8M7**
Restaurants controller now renders the homepage, the json is no longer needed.
Tomorrow we/I will get to work on the home page, either log in directly or view available Tickets.'

As far as configuration goes for devise. Last week most groups tried to brute force it which didn't work as expected (which is good, security is good). Fortunately there are very easy ways to login with a username as opposed to an email, set custom login messages and multitudes of easily, highly configurable options. I will update it accordingly depending on what we want information is required from a user and what we will use that user for.

### CODE REVIEW

**Comment by mtthwgry** [comment]
we specifically talked about not using devise...

**Comment by tr8M7** [comment]
Why reinvent the wheel?

**Comment by mtthwgry** [comment]
because I know how to build a wheel.

**Comment by tr8M7** [comment]
Closing this for now until we have restaurants tied to users.

**Pull request closed without merging**
